---
- hosts: all
  gather_facts: yes
  become: true

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  vars:
    remote_user: vagrant
    docker_network_name: ghost_network
    pip_install_packages:
      - docker
      - docker-compose

  tasks:
  #   - name: install docker
  #     apt_key:
  #       keyserver: hkp://p80.pool.sks-keyservers.net:80
  #       id: 58118E89F3A912897C070ADBF76221572C52609D
  #   - name: add deb repo
  #     apt_repository:
  #      filename: docker.list
  #      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
  #      state: present
  #   - name: install docker
  #     apt: name=docker-engine state=present
    - name: add user mod
      user:
        name: "{{ remote_user }}"
        groups: docker
        append: yes

  #   - name: install pip
  #     apt: name=python-pip state=present

  #   - name: Ensure old module not present
  #     pip:
  #       name: docker-py
  #       state: absent
  #   - name: Install pip modules on target box
  #     pip:
  #       name: "{{ item }}"
  #       state: present
  #     with_items:
  #       - docker
  #       - docker-compose

    - name: create ghost network
      docker_network:
        name: "{{ docker_network_name }}"

    - name: Launch ghost blog
      docker_container:
        name: ghost
        image: "ghost:0.11.12"
        networks:
          - name: "{{ docker_network_name }}"

    #     env_file: ghost.env
    #    volumes:
    #      - "{{ playbook_dir }}/ghost:/var/lib/ghost"
    # - name: Launch nginx
    #   docker:
    #     name: nginx
    #     image: nginx
    #     volumes:
    #       - "{{ playbook_dir }}/nginx.conf:/etc/nginx/nginx.conf"
    #     ports:
    #       - 80:80
