---
- hosts: all
  gather_facts: yes
  become: true

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  vars:
    remote_user: vagrant
    docker_network_name: ghost_network
    pip_install_packages:
      - docker
      - docker-compose

  tasks:
    - name: add user mod
      user:
        name: "{{ remote_user }}"
        groups: docker
        append: yes

    - name: create ghost content dir
      file:
        path: /var/lib/ghost/content
        state: directory
        mode: 0755

    - name: create ghost network
      docker_network:
        name: "{{ docker_network_name }}"

    - name: launch ghost blog
      docker_container:
        name: ghost
        image: "ghost:1.19.2"
        volumes:
          /var/lib/ghost/content:/var/lib/ghost/content
        networks:
          - name: "{{ docker_network_name }}"

    - name: copy nginx.conf to remote
      copy:
        src: nginx.conf
        dest: "{{ ansible_env.HOME }}/nginx.conf"

    - name: launch nginx
      docker_container:
        name: nginx
        image: "nginx"
        volumes:
          - "{{ ansible_env.HOME }}/nginx.conf:/etc/nginx/nginx.conf"
        ports:
          - 80:80
        networks:
          - name: "{{ docker_network_name }}"

    #     env_file: ghost.env
    #    volumes:
    #      - "{{ playbook_dir }}/ghost:/var/lib/ghost"
    # - name: Launch nginx
    #   docker:
    #     name: nginx
    #     image: nginx
    #     volumes:
    #       - "{{ playbook_dir }}/nginx.conf:/etc/nginx/nginx.conf"
    #     ports:
    #       - 80:80
